### ISSUE TITLE
Highlight current section in the TOC on the right

### ISSUE THREAD

**Issue by kaushalmodi** [carsonip/hugo-theme-minos#1]
Hi,

I like the simplicity of your theme and the TOC shown on the right.

Can you please add few features to the TOC if you have time:

- Highlight the current section in the TOC. So if the top of the browser is after section 2, the TOC should highlight section 2.
- When the TOC length is greater than the browser height, if the user scrolls to a section that is currently not visible in the TOC, the TOC should scroll along with page scroll, and end up showing the section in the TOC, highlighted.

If the above explanation is too abstract, I am talking about the TOC behavior as in twitter bootstrap -- [example](https://getbootstrap.com/getting-started/).

**Comment by carsonip** [comment]
Thanks! This feature is not available in the original Hexo theme and that's why it isn't here. However, I would love to implement this. It should be ready in a few days.

**Comment by kaushalmodi** [comment]
To add a 3rd bullet to my OP:

- Auto-expand/collapse sub-sections too

All of this behavior can be seen by mouse-scrolling up/down on that [example page](https://getbootstrap.com/getting-started/).

Thanks!

**Comment by carsonip** [comment]
Got it. I'll probably make the "auto-expand and collapse" feature optional tho.

**Comment by carsonip** [comment]
This is a great feature. I'll consider making smart TOC the default in the future.

**Comment by kaushalmodi** [comment]
Thanks. I tried out the theme. I see the TOC on the right if I do not set SmartToc. But if I set it, the `display: none;` makes the TOC hide, but then the javascript doesn't seem to be doing anything.

Do I need to anything more to make this work? Thanks.

**Comment by carsonip** [comment]
My bad. I did not consider the case that the top layer is `##` instead of `#`. The bug is fixed in cbe7676c741bb5289d1abf2a7f2a298e19881459.

**Comment by kaushalmodi** [comment]
Thanks for the fix attempt. But it is still not working for me.

I am simply using the basic Hugo site example used by all themes. I have provided a PR (https://github.com/carsonip/hugo-theme-minos/pull/2) that just added that example to this theme.

You need to then:

- cd to `exampleSite`
- `hugo serve`

With that, I still don't see the TOC on the right with `SmartToc` set to `true`.

---

If it helps, I am using the master branch of hugo; version:

> Hugo Static Site Generator v0.19-DEV-0EB76B08 linux/amd64 BuildDate: 2017-02-26T00:43:11-05:00

**Comment by carsonip** [comment]
I tried the example in your PR. It works well for me, even if I am using your version of hugo. May I ask what browser and version are you using? I am using jQuery 3.1.1 in smart TOC and may not work in some older browsers.

**Comment by kaushalmodi** [comment]
Thanks for verifying. I am away from my computer, so I cannot tell the exact version, but I am using Firefox. 

Also if it helps, the "smarttoc" behavior on the reference site I linked above (https://getbootstrap.com/getting-started/) is working fine on the same browser. 

Apologies, but I have zero knowledge about JavaScript. Would be great if you can get this feature to work for a wider range of browsers (not asking IE :)), but at least for Firefox and Chrome.

Once I get to the computer, I'll try it out on Chrome too.

**Comment by carsonip** [comment]
Weird. I tried it on both Chrome 56 and Firefox 51 and both of them worked well. Please let me know your Firefox version though. Please also let me know if there is any error log in the web console.

**Comment by kaushalmodi** [comment]
>  I tried it on both Chrome 56 and Firefox 51 

I am on Chrome 49.0.2623.110 and Firefox 45.0.1 (esr update channel) -- sorry, I don't have control on these versions as they are updated by the sysadmin (work).

Good news is that it works on Chrome.

Probably good news is that I can see an error happening on Firefox (so, it can be fixed? :))

![image](https://cloud.githubusercontent.com/assets/3578197/23342753/f0f0f3c2-fc2d-11e6-8644-20582ca14e96.png)

![image](https://cloud.githubusercontent.com/assets/3578197/23342756/0576a436-fc2e-11e6-83d2-17a1b7c4d64b.png)

Would that help fix this for the old Firefox?

**Comment by kaushalmodi** [comment]
>  I am using jQuery 3.1.1 in smart TOC and may not work in some older browsers.

More info.. *view-source:https://getbootstrap.com/getting-started/* shows that that site is using *jQuery 1.12.4*.

So probably that partially explains why that site works on my old Firefox?

**Comment by kaushalmodi** [comment]
Looks like I happened to find the fix? :)

Firefox needs the `onScroll` function to be defined before it can be used?

```js
             if ($toc.length > 0) {
                 var $window = $(window);

                 function onScroll(){
                     var currentScroll = $window.scrollTop();
                     var h = $('.article-entry h1, .article-entry h2, .article-entry h3, .article-entry h4, .article-entry h5, .article-entry h6');
                     var id = "";
                     h.each(function (i, e) {
                         e = $(e);
                         if (e.offset().top - 10 <= currentScroll) {
                             id = e.attr('id');
                         }
                     });
                     var active = $toc.find('a.active');
                     if (active.length == 1 && active.eq(0).attr('href') == '#' + id) return true;

                     active.each(function (i, e) {
                         $(e).removeClass('active').siblings('ul').hide();
                     });
                     $toc.find('a[href="#' + id + '"]').parentsUntil('#TableOfContents').each(function (i, e) {
                         $(e).children('a').addClass('active').siblings('ul').show();
                     });
                 }

                 $window.on('scroll', onScroll);
                 $(document).ready(function() {
                     $toc.find('a').parent('li').siblings('ul').hide();
                     onScroll();
                     document.getElementsByClassName('article-toc')[0].style.display = '';
                 });
             }
```
